services:
  socket-lab:
    build: ./socket-lab
    image: socket-lab
    container_name: socket-lab
    environment:
      - APP=server
    ports:
      - "8080:8080"

  rest-api-lab:
    build: ./rest-api-lab
    image: rest-api-lab
    container_name: rest-api-lab
    ports:
      - "8081:8081"

  grpc-lab:
    build: ./grpc-lab
    image: grpc-lab
    container_name: grpc-lab
    ports:
      - "50051:50051"