# chaos experiment configuration for chaos toolkit
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-experiment
data:
  experiment.json: |
    {
      "version": "1.0.0",
      "title": "Client Service Resilience Test",
      "description": "Verify client service resilience when server service fails",
      "tags": ["kubernetes", "resilience"],
      "steady-state-hypothesis": {
        "title": "Services are running normally",
        "probes": [
          {
            "type": "probe",
            "name": "server-service-available",
            "tolerance": 200,
            "provider": {
              "type": "http",
              "url": "http://server-service:8080/api/hello",
              "timeout": 5
            }
          }
        ]
      },
      "method": [
        {
          "type": "action",
          "name": "terminate-server-pod",
          "provider": {
            "type": "python",
            "module": "chaosk8s.pod.actions",
            "func": "terminate_pods",
            "arguments": {
              "label_selector": "app=server",
              "name_pattern": "server-",
              "rand": true
            }
          }
        },
        {
          "type": "action",
          "name": "wait-for-recovery",
          "provider": {
            "type": "process", 
            "path": "sleep",
            "arguments": "20"
          }
        },
        {
          "type": "probe",
          "name": "verify-server-service-recovered",
          "provider": {
            "type": "http",
            "url": "http://server-service:8080/api/hello",
            "timeout": 5
          },
          "tolerance": 200
        }
      ],
      "rollbacks": []
    }

    
---
# Service Account offering identity for Chaos Toolkit
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-service-account


---
# Cluster Role with necessary permissions for Chaos Toolkit
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]


---
# Bind the Service Account to the Cluster Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-cluster-binding
subjects:
- kind: ServiceAccount
  name: chaos-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: chaos-cluster-role
  apiGroup: rbac.authorization.k8s.io


---
# Deployment for Chaos Toolkit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-toolkit
  template:
    metadata:
      labels:
        app: chaos-toolkit
    spec:
      serviceAccountName: chaos-service-account
      containers:
      - name: chaos-toolkit
        image: chaostoolkit/chaostoolkit
        command: 
        - "/bin/sh"
        - "-c"
        args:
        - |
          echo "Installing required packages..."
          pip install chaostoolkit-kubernetes chaostoolkit-lib
          echo "Starting chaos toolkit container..."
          sleep infinity
        env:
        - name: CHAOSTOOLKIT_IN_POD
          value: "true"
        volumeMounts:
        - name: experiment-volume
          mountPath: /tmp/experiments
      volumes:
      - name: experiment-volume
        configMap:
          name: chaos-experiment